### ISSUE TITLE
Dropdown Toggle Accessibility

### ISSUE THREAD

**Issue by laneparton** [react-restart/ui#44]
## Is your feature request related to a problem? Please describe

According to [these aria guidelines](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html), "enter" is a valid key to toggle a dropdown, but doesn't appear to be supported in this package's Dropdown component.

## Describe the solution you'd like

Add a keydown event for the "enter" key to open a dropdown.

## Additional context

I'm happy to open a PR. My primary goal with this issue is to make sure its a valid request.

https://github.com/react-bootstrap/react-bootstrap/issues/5596#issuecomment-1016499010

**Comment by jquense** [comment]
I'm not sure honestly. The "logic" now is we just "click" as a trigger and let the browser decide which keyboard buttons that means, the issue here is that for `button` elements, it is `space` and for `a` links, it's `enter`. Bootstrap upstream does the same thing i think. 

I'm ok making it consistent i think. @kyletsang thoughts? PR would go in `restart/ui` i think

**Comment by kyletsang** [comment]
This appears to be caused by a missing `href="#"` in the dropdown toggle anchor.  The anchor in the bs4 branch defaults to "#" if it's a trivial href.  We should probably do the same in the anchor here?

https://github.com/react-bootstrap/react-bootstrap/blob/c4167fbd592ba45cd73f06ab642450c5e8d76d9a/src/SafeAnchor.tsx#L81

**Comment by paintingandvino** [comment]
@kyletsang Confirming what you already know ;)

But adding `href="#"` to the DOM on the [react-bootstrap documentation](https://react-bootstrap.netlify.app/components/navs/#using-dropdowns) dropdown fixes this issue.
